#!/usr/bin/env python3
from PIL import Image
from images import pad_image_to_landscape, save_image
import argparse
import sys


def rotate_image(image_file_name, degrees, delete_original):
    img = Image.open(image_file_name)
    img = img.rotate(degrees, expand=True)
    if img.height > img.width:
        img = pad_image_to_landscape(img)
    save_image(img, image_file_name, delete_original)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Rotate image CW or CCW')

    parser.add_argument('image_file_name', help='Name of image to rotate')
    parser.add_argument('-d', '--direction', type=str, required=True, help='Direction to rotate (cw or ccw)')
    parser.add_argument('-D', '--delete-original', action='store_true', default=False)
    args = parser.parse_args()

    degrees = 0
    if args.direction.lower() == 'cw':
        degrees = 270
    elif args.direction.lower() == 'ccw':
        degrees = 90
    else:
        print('Invalid direction "%s" must be "cw" or "ccw"', args.direction)
        sys.exit(-1)

    rotate_image(args.image_file_name, degrees, args.delete_original)